version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:v3
  backend_user-api:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:v4
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:v4
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:v2