apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-api
  labels:
    app: backend-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user-api
  template:
    metadata:
      labels:
        app: backend-user-api
    spec:
      containers:
      - name: backend-user-api
        image: zyzornatti/udagram-api-user:v2-latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m        
        envFrom:
          - configMapRef:
              name: udagram-env
          - secretRef:
              name: udagramdb-env
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: udagram-aws-env
      volumes:
        - name: udagram-aws-env
          configMap: 
            name: udagram-env