version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
 build:
  docker:
      - image: 
	 - zyzornatti/udagram-api-feed
	 - zyzornatti/udagram-api-user
	 - zyzornatti/udagram-frontend
	 - zyzornatti/reverseproxy

  steps:
    - checkout
    - setup_remote_docker
    # build and push Docker image
    - run: |
	#build
         - docker build -t udagram-api-feed ./udagram-api-feed
         - docker build -t udagram-api-user ./udagram-api-user
         - docker build -t udagram-frontend ./udagram-frontend
         - docker build -t udagram-reverseproxy ./reverseproxy

	#Tag
         - docker tag udagram-api-feed zyzornatti/udagram-api-feed:v1
         - docker tag udagram-api-user zyzornatti/udagram-api-user:v1
         - docker tag udagram-frontend zyzornatti/udagram-frontend:v1
         - docker tag reverseproxy zyzornatti/reverseproxy:v1

	#Auth
	 echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

	#push
         - docker push zyzornatti/udagram-api-feed:v1
         - docker push zyzornatti/udagram-api-user:v1
         - docker push zyzornatti/udagram-api-frontend:v1
         - docker push zyzornatti/reverseproxy:v1

workflows:
 build_push_docker:
   jobs:
     - build
 monthly_update:
   triggers:
     - schedule:
	 cron: "0 0 3 * *"
	 filters:
	   branches:
	     only:
		- main
 jobs:
  - build
  - node/test:
       version: '13'
       pkg-manager: npm
  