version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
 build:
  docker:
      - image: zyzornatti/udagram-api-feed
      - image: zyzornatti/udagram-api-user
      - image: zyzornatti/udagram-frontend
      - image: zyzornatti/reverseproxy

  steps:
    - checkout
    - setup_remote_docker
    # build and push Docker image
    - run: |
        #build
         - docker build -t udagram-api-feed ./udagram-api-feed
         - docker build -t udagram-api-user ./udagram-api-user
         - docker build -t udagram-frontend ./udagram-frontend
         - docker build -t udagram-reverseproxy ./reverseproxy

        #Tag
         - docker tag udagram-api-feed zyzornatti/udagram-api-feed:latest
         - docker tag udagram-api-user zyzornatti/udagram-api-user:latest
         - docker tag udagram-frontend zyzornatti/udagram-frontend:latest
         - docker tag reverseproxy zyzornatti/reverseproxy:latest

        #Auth
          echo DOCKER_PASSWORD | docker login -u DOCKER_USERNAME --password-stdin

        #push
         - docker push zyzornatti/udagram-api-feed:latest
         - docker push zyzornatti/udagram-api-user:latest
         - docker push zyzornatti/udagram-api-frontend:latest
         - docker push zyzornatti/reverseproxy:latest


  