language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./reverseproxy
# Tagging
  - docker tag udagram-api-feed zyzornatti/udagram-api-feed:v1
  - docker tag udagram-api-user zyzornatti/udagram-api-user:v1
  - docker tag udagram-frontend zyzornatti/udagram-frontend:v1
  - docker tag reverseproxy zyzornatti/reverseproxy:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker push zyzornatti/udagram-api-feed:v1
  - docker push zyzornatti/udagram-api-user:v1
  - docker push zyzornatti/udagram-api-frontend:v1
  - docker push zyzornatti/reverseproxy:v1